### PR TITLE
Self check for dependencies

### PR DESCRIPTION
**Pull request by fluca1978**
Since the script relies on other tools, better check for them before starting a build process.

### CODE REVIEW

**Comment by theory** [comment]
This is great! Would you mind making a few tweaks?

* Exit with a value of 1 on error (e.g., `exit 1`)
* Report all misting programs before exiting
* I don't think you need to check for download failure, because `set -x` makes is so that the script exits if `curl` exits with an error

Thank you!

**Comment by fluca1978** [comment]
Should work as you asked now.
I'm not sure about removing the tarball check, since `set -e` works for bash, not sure for other shells.

**Comment by fluca1978** [comment]
Shame on me, the sheband is already for bash.

**Comment by theory** [comment]
So are `grep`, `wc`, and `cat` now also required commands? 😂

**Comment by theory** [comment]
Note that I work around an issue with premature exit when `which` failed to find a dependency. The use of `trap` gives us more flexibility in any event. Oddly, however, when I turn `exit` back on at line 111, it properly exits if `wc` returns an error, but not if `cat` or `grep` does. :-(

**Pull request merged**
